name: "Invoke-PSDepend"
description: "Install dependencies by Invoke-PSDepend."
author: "Sergey.S.Betke@yandex.ru"
branding:
  icon: "download"
  color: blue
inputs:
  version:
    description: "PSDepend required version"
    required: false
    default: "latest"
  recurse:
    description: "parse .depend.psd1 recursive"
    required: false
    default: "true"
  verbose:
    description: "verbose PSDepend output"
    required: false
    default: "true"
runs:
  using: "composite"
  steps:
    - id: main
      shell: powershell
      run: |
        . "${{ github.action_path }}/Invoke-GitHubAction.ps1";
